symfony/tennis_club/src/Entity/Cours.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CoursRepository")
 */
class Cours
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateCours;

    /**
     * @ORM\Column(type="integer")
     */
    private $DureeCours;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Staff")
     */
    private $IDCoachCours;

    /**
     * @ORM\Column(type="integer")
     */
    private $EffectifCours;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\CompteClient", inversedBy="inscriptions")
     */
    private $inscriptions;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCours(): ?\DateTimeInterface
    {
        return $this->DateCours;
    }

    public function setDateCours(\DateTimeInterface $DateCours): self
    {
        $this->DateCours = $DateCours;

        return $this;
    }

    public function getDureeCours(): ?int
    {
        return $this->DureeCours;
    }

    public function setDureeCours(int $DureeCours): self
    {
        $this->DureeCours = $DureeCours;

        return $this;
    }

    public function getIDCoachCours(): ?Staff
    {
        return $this->IDCoachCours;
    }

    public function setIDCoachCours(?Staff $IDCoachCours): self
    {
        $this->IDCoachCours = $IDCoachCours;

        return $this;
    }

    public function getEffectifCours(): ?int
    {
        return $this->EffectifCours;
    }

    public function setEffectifCours(int $EffectifCours): self
    {
        $this->EffectifCours = $EffectifCours;

        return $this;
    }

    /**
     * @return Collection|CompteClient[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(CompteClient $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
        }

        return $this;
    }

    public function removeInscription(CompteClient $inscription): self
    {
        if ($this->inscriptions->contains($inscription)) {
            $this->inscriptions->removeElement($inscription);
        }

        return $this;
    }
    
}

symfony/tennis_club/src/Entity/Evenement.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EvenementRepository")
 */
class Evenement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $TitreEvenements;

    /**
     * @ORM\Column(type="text")
     */
    private $DetailsEvenements;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateEvenements;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaires", mappedBy="Evenement", orphanRemoval=true)
     */
    private $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreEvenements(): ?string
    {
        return $this->TitreEvenements;
    }

    public function setTitreEvenements(string $TitreEvenements): self
    {
        $this->TitreEvenements = $TitreEvenements;

        return $this;
    }

    public function getDetailsEvenements(): ?string
    {
        return $this->DetailsEvenements;
    }

    public function setDetailsEvenements(string $DetailsEvenements): self
    {
        $this->DetailsEvenements = $DetailsEvenements;

        return $this;
    }

    public function getDateEvenements(): ?\DateTimeInterface
    {
        return $this->DateEvenements;
    }

    public function setDateEvenements(\DateTimeInterface $DateEvenements): self
    {
        $this->DateEvenements = $DateEvenements;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setEvenement($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getEvenement() === $this) {
                $commentaire->setEvenement(null);
            }
        }

        return $this;
    }
}

symfony/tennis_club/templates/pages/affichage_cours.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Liste des cours </h1>

<ul>
{% for c in cours %}
<li><b>Date : </b> {{c.DateCours | date('d/m/Y à H:i')}} <br/> <b>Duree : </b> {{c.DureeCours}} <br/> <b>Effectifs : </b> {{c.effectifCours}} <br/> <b>Dirigé par : </b> {{c.IDCoachCours.renseignements.nom}}    {{c.IDCoachCours.renseignements.prenom}}   <br/><br/> <a href="{{path('inscription_cours',{'id' : c.id })}}"><button type="submit" class = "btn btn-success">S'inscrire</button></a><br/><br/><br/></li>
{% endfor %}
</ul>


{% endblock %}

symfony/tennis_club/templates/pages/ajout_cours.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Ajout de cours</h1>
{{form_start(formulaire)}}
{{form_row(formulaire.DateCours)}}
{{form_row(formulaire.DureeCours, {'label': 'Duree', attr: {'placeholder': "duree", 'class' : "form-control"}})}}
{{form_row(formulaire.EffectifCours, {'label': 'Effectifs', attr: {'placeholder': "effectifs", 'class' : "form-control"}})}}
{{form_row(formulaire.IDCoachCours, {'label': 'le coach'})}}
<button type="submit" class = "btn btn-success">Ajouter le cours</button>
{{form_end(formulaire)}}
{% endblock %}

symfony/tennis_club/templates/pages/ajout_staff.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Ajout de staff</h1>

{{form_start(formulaire)}}
{{form_row(formulaire.renseignements, {'label': 'Nom du staff', attr: {'placeholder': "nom du staff", 'class' : "form-control"}})}}
{{form_row(formulaire.role, {'label': 'Role du staff', attr: {'placeholder': "role du staff", 'class' : "form-control"}})}}

<button type="submit" class = "btn btn-success">Enregistrer</button>
{{form_end(formulaire)}}
{% endblock %}

symfony/tennis_club/templates/pages/forum.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<h1>Sujets</h1>

{% for s in sujet %}
{% if s.id % 4 == 1 %}
<a href= "{{path ('posts', { 'id' : s.id } ) }}" >
<p class = "alert alert-success"><b>{{s.TitreTopic}}</b> <br/> <i>{{s.IDAuteurTopic.pseudo}}</i></p>
</a>
{% elseif s.id % 4 == 2 %}
<a href= "{{path ('posts', { 'id' : s.id } ) }}" >
<p class = "alert alert-warning"><b>{{s.TitreTopic}}</b> <br/> <i>{{s.IDAuteurTopic.pseudo}}</i></p>
</a>
{% elseif s.id % 4 == 3 %}
<a href= "{{path ('posts', { 'id' : s.id } ) }}" >
<p class = "alert alert-danger"><b>{{s.TitreTopic}}</b> <br/> <i>{{s.IDAuteurTopic.pseudo}}</i></p>
</a>
{% else %}
<a href= "{{path ('posts', { 'id' : s.id } ) }}" >
<p class = "alert alert-info"><b>{{s.TitreTopic}}</b> <br/> <i>{{s.IDAuteurTopic.pseudo}}</i></p>
</a>
{% endif %}

{% endfor %}
{% if app.user %}
{{form_start(formulaire)}}
{{form_row(formulaire.TitreTopic, {'label': 'Titre du sujet', attr: {'placeholder': "Titre"}})}}

<button type="submit" class = "btn btn-success">+</button>
{{form_end(formulaire)}}

{% else %}
<br/><br/><br/>
<h3><b>Veuillez vous connecter pour ajouter un nouveau sujet</b></h3>
{% endif %}
{% endblock %}

symfony/tennis_club/templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1> Liste de tous les evenements </h1>
    {% for evt in event %}
    <h4>{{ evt.TitreEvenements }}</h4> 
    {{ evt.DetailsEvenements | raw }}
    <p><i>{{ evt.dateEvenements | date('d/m/Y H:i')}}</i></p>
    {% if app.user %}
 <a href="{{path('commentaires_evenement',{'id' : evt.id})}}"><button type="submit" class = "btn btn-warning">Voir les réactions</button></a>
    {% if is_granted('ROLE_USER') %}
    <br/><br/><br/>
    {% endif %}
    {% endif %}
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{path('supprimer_evenement',{'id' : evt.id})}}"><button type="submit" class = "btn btn-danger">supprimer l'événement</button></a>
    <br/><br/><br/>
    {% endif %}

    {% endfor %}

{% if is_granted('ROLE_ADMIN') %}
<h3>Ajout d'un evenement</h3>
{{form_start(formulaire)}}
{{form_widget(formulaire)}}
<button type="submit" class = "btn btn-success">Envoyer</button>
{{form_end(formulaire)}}
{% endif %}
    {% endblock %}

symfony/tennis_club/templates/pages/mes_cours.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Liste de mes cours</h1>
<ul>
{% for inscr in inscription %}
<li><b>Date : </b> {{inscr.DateCours | date('d/m/Y à H:i')}} <br/> <b>Duree : </b> {{inscr.DureeCours}} <br/> <b>Effectifs : </b> {{inscr.effectifCours}} <br/> <b>Dirigé par : </b> {{inscr.IDCoachCours.renseignements.nom}}    {{inscr.IDCoachCours.renseignements.prenom}}   <br/><br/><br/></li>

{% endfor %}

{% endblock %}

symfony/tennis_club/templates/pages/posts.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<br/><br/>
<div class="card">
{% if sujet.id % 4 == 1 %}
<div class="card-header alert-success">
{% elseif sujet.id % 4 == 2 %}
<div class="card-header alert-warning">
{% elseif sujet.id % 4 == 3 %}
<div class="card-header alert-danger">
{% else %}
<div class="card-header alert-info">
{% endif %}
    {{sujet.TitreTopic}}
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">



{% for p in posts %}

<div class="card">
<div class="card-header alert-primary">
{% if p.IDAuteurPost.avatar != "" %}
<img src="{{p.IDAuteurPost.avatar}}" alt="{{p.IDAuteurPost.pseudo}}" width = "30px" />
{% endif %}
    {{p.IDAuteurPost.pseudo}}
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{p.TextePost | raw}}</p>
      <footer class="blockquote-footer">{{p.DatePost | date('d/m/Y')}} {{p.DatePost | date('H:i:s')}}</footer>
    </blockquote>
  </div>
</div>
<br/><br/>
{% endfor %}

    </blockquote>
  </div>
</div>

{% if app.user %}
<br/><br/><br/>
{{form_start(formulaire)}}
{{form_row(formulaire.TextePost, {'label': 'Ajouter un commentaire', attr: {'placeholder': "Texte du poste"}})}}
<button type="button" id="gras" name="gras"onClick="javascript:bbcode('[g]', '[/g]');return(false)"><b>G</b></button>
<button type="button" id="italique" name="italique"onClick="javascript:bbcode('[i]', '[/i]');return(false)"><em>i</em></button>
<button type="button" id="souligne" name="souligne"onClick="javascript:bbcode('[s]', '[/s]');return(false)"><u>s</u></button>
<img src="../images/smileys/smiley1.png" title="mario" alt="mario" onClick="javascript:smilies(':c)');return(false)" />
<img src="../images/smileys/smiley2.png" title="inquiet" alt="inquiet" onClick="javascript:smilies(':o');return(false)" />
<img src="../images/smileys/smiley3.png" title="heureux" alt="heureux" onClick="javascript:smilies(':D');return(false)" />
<img src="../images/smileys/smiley4.png" title="fleur" alt="fleur" onClick="javascript:smilies(':)');return(false)" />
<img src="../images/smileys/smiley5.png" title="triste" alt="triste" onClick="javascript:smilies(':(');return(false)" />
<br/><br/>
<button type="submit" class = "btn btn-success">Envoyer</button>
{{form_end(formulaire)}}

{% else %}
<br/><br/><br/>
<h3><b>Veuillez vous connecter pour pouvoir discuter</b></h3>
{% endif %}


<script>
function bbcode(bbdebut, bbfin)
{
var input = window.document.post.post_TextePost;
input.focus();
if(typeof document.selection != 'undefined')
{
var range = document.selection.createRange();
var insText = range.text;
range.text = bbdebut + insText + bbfin;
range = document.selection.createRange();
if (insText.length == 0)
{
range.move('character', -bbfin.length);
}
else
{
range.moveStart('character', bbdebut.length + insText.length + bbfin.length);
}
range.select();
}
else if(typeof input.selectionStart != 'undefined')
{
var start = input.selectionStart;
var end = input.selectionEnd;
var insText = input.value.substring(start, end);
input.value = input.value.substr(0, start) + bbdebut + insText + bbfin + input.value.substr(end);
var pos;
if (insText.length == 0)
{
pos = start + bbdebut.length;
}
else
{
pos = start + bbdebut.length + insText.length + bbfin.length;
}
input.selectionStart = pos;
input.selectionEnd = pos;
}
 
else
{
var pos;
var re = new RegExp('^[0-9]{0,3}$');
while(!re.test(pos))
{
pos = prompt("insertion (0.." + input.value.length + "):", "0");
}
if(pos > input.value.length)
{
pos = input.value.length;
}
var insText = prompt("Veuillez taper le texte");
input.value = input.value.substr(0, pos) + bbdebut + insText + bbfin + input.value.substr(pos);
}
}

function smilies(img)
{
window.document.post.post_TextePost.value += '' + img + '';
}
</script>
{% endblock %}

symfony/tennis_club/templates/pages/reaction.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>{{evenement.TitreEvenements}}</h1>
<p>{{evenement.DetailsEvenements}}</p>
{% for com in commentaire %}
<div class="card border-secondary mb-3">
  <div class="card-header">{{com.Date | date('d/m/Y')}} {{com.Date | date('H:i:s')}}</div>
  <div class="card-body text-secondary">
    <h5 class="card-title">{{com.Auteur.pseudo}}</h5>
    <p class="card-text">{{com.Texte}}</p>
  </div>
</div>
{% endfor %}

{% if app.user %}
<br/><br/><br/>
{{form_start(formulaire)}}
{{form_row(formulaire.texte, {'label': 'Ajouter un commentaire', attr: {'placeholder': "Texte du commentaire"}})}}
<button type="submit" class = "btn btn-success">+</button>
{{form_end(formulaire)}}

{% else %}
<br/><br/><br/>
<h3><b>Veuillez vous connecter pour pouvoir discuter</b></h3>
{% endif %}
{% endblock %}

symfony/tennis_club/templates/pages/recherche.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Recherche de {{option}}</h1>

{% if option == "Utilisateur" %}
<ul>
{% for elem in element %}

<li><b>Nom : </b> {{ elem.nom }} <br/> <b>Prenom : </b> {{elem.prenom}} <br/> <b>Date de Naissance : </b> {{elem.Tel | date('d/m/Y')}} <br/> <b>Tel : </b> {{ elem.tel }} <br/> <b>Mail : </b> {{ elem.mail }} <br/><br/><br/></li>
{% endfor %}
</ul>


{% elseif option == "Cours" %}

<ul>
{% for elem in element %}

<li><b>Date : </b> {{elem.DateCours | date('d/m/Y à H:i')}} <br/> <b>Duree : </b> {{elem.DureeCours}} <br/> <b>Effectifs : </b> {{elem.effectifCours}} <br/> <b>Dirigé par : </b> {{elem.IDCoachCours.renseignements.nom}}    {{elem.IDCoachCours.renseignements.prenom}}   <br/><br/><br/></li>
{% endfor %}
</ul>

{% else %}

<ul>
{% for elem in element %}

<li><b>Titre : </b> {{elem.TitreEvenements}} <br/> <b>Date de parution : </b> {{elem.DateEvenements | date('d/m/Y H:i')}} <br/><br/><br/></li>
{% endfor %}
</ul>

{% endif %}
{% endblock %}

symfony/tennis_club/templates/pages/staffs.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Contacts</h1>
<ul>
{% for s in staff %}
<li>{% if s.renseignements.avatar != "" %} <img src="{{s.renseignements.avatar}}" alt="{{s.renseignements.pseudo}}" width = "60px" /> {% endif %} <h5>{{s.renseignements.nom}} {{s.renseignements.prenom}}</h5><b>Role : </b> {{s.role}} <br/> <b>Tel : </b> {{s.renseignements.tel}} <br/> <b>Mail : </b> <a href= "mailto:{{s.renseignements.mail}}">{{s.renseignements.mail}}</a><br/><br/><br/></li>
{% endfor %}
</ul>
{% endblock %}